### ISSUE TITLE
Readme example does not work

### ISSUE THREAD

**Issue by jasongi** [dashed/sizeof-loader#1]
Currently in the readme it has the following usage:
`                        loader: require.resolve(
                            "./loaders/custom-image-size-loader"
                        ),
`
If you have installed with npm/yarn should simply be:
`                        loader: "sizeof-loader",
`

**Comment by dashed** [comment]
@jasongi Good catch! Accidentally copied the webpack config at the time when `sizeof-loader` didn't exist. 😅 

Will fix this promptly.
